name: Test Implementation
on:
  push:
    branches: '*'
  pull_request:
  workflow_dispatch:
concurrency:
  group: Test Implementation
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the repository
        uses: actions/checkout@main  # Replace 'main' with 'v4' when problems arise with updates.
      - name: Setting up Python 3.12.2
        uses: actions/setup-python@main  # Replace 'main' with 'v5' when problems arise with updates.
        with:
          python-version: '3.12.2'
      - name: Installing requirements for the project
        run: python -m pip install -r requirements.txt
      - name: Running tests
        run: python -m pytest Tests/
